### PR TITLE
Changed all occurrences of athena to schoology

### PR DESCRIPTION
**Pull request by chiragzq**

### CODE REVIEW

**Comment by chiragzq** [comment]
Changed permissions back from 755 to 644

**Comment by chiragzq** [comment]
Changed permission of directories to 755

**Comment by chiragzq** [comment]
Updated spaces to tabs

**Comment by rianadon** [comment]
Looks awesome Chirag!

Thanks so much for all the changes and dealing with my formatting requests. I'll merge this with `dev` for now then merge `dev` with `master` once I write up an update message.

Congrats on being the first person to write a pull request for Check PCR! :grin:

**Comment by Shounak-Ghosh** [comment]
lol nice shifarg

**Pull request merged**
